# Generated by Django 2.2 on 2019-12-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='user_pics', verbose_name='Photo')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('like', models.IntegerField(default=0, verbose_name='Raiting')),
                ('author', models.CharField(max_length=20, verbose_name='Added by')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Comment')),
                ('comment_author', models.CharField(max_length=20, verbose_name='Added by')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment', to='webapp.Photo', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
